[Unit]
ConditionPathExists=!/var/lib/dank-bluebuild/system-flatpak-setup.completed

[Service]
ExecStartPost=/usr/bin/touch /var/lib/dank-bluebuild/system-flatpak-setup.completed

[Install]
WantedBy=multi-user.target