[Unit]
ConditionPathExists=!%h/.local/state/dank-bluebuild/user-flatpak-setup.completed

[Service]
ExecStartPost=/usr/bin/touch %h/.local/state/dank-bluebuild/user-flatpak-setup.completed

# [Install]
# WantedBy=default.target