[Unit]
Requisite=dms.service
After=dms.service
ConditionPathExists=!%h/.local/state/dank-bluebuild/user-flatpak-setup.completed

[Service]
ExecStartPost=/usr/bin/touch %h/.local/state/dank-bluebuild/user-flatpak-setup.completed

[Install]
WantedBy=dms.service