#!/usr/bin/env bash

set -euo pipefail

# shellcheck disable=SC2329
on_interrupt() {
    trap - INT TERM
    echo "Script interrupted." >&2
    exit 130
}
trap on_interrupt INT TERM

echo "Disabling default user Flatpak auto-reinstall..."

failed() {
    echo "Failed to disable default user Flatpak auto-reinstall." >&2
    exit 1
}

bluebuild-flatpak-manager disable user || failed

echo "Successfully disabled default user Flatpak auto-reinstall."
exit 0

