#!/usr/bin/env bash

set -euo pipefail

# shellcheck disable=SC2329
abort_script() {
    echo "Script interrupted." >&2
    exit 1
}
trap abort_script INT

echo "Disabling default user Flatpak auto-reinstall..."

failed() {
    echo "Failed to disable default user Flatpak auto-reinstall." >&2
    exit 1
}

bluebuild-flatpak-manager disable user || failed

echo "Successfully disabled default user Flatpak auto-reinstall."
exit 0

