[terminal]
vt = 1

[default_session]
user = "greeter"

### Uncomment to run the greeter on Hyprland
command = "dms-greeter --command hyprland"
### Uncomment the below line to run the greeter on Niri
# command = "dms-greeter --command niri"
### Uncomment to run the greeter on sway
# command = "dms-greeter --command sway"
### Uncomment to run the greeter on Miracle WM
# command = "dms-greeter --command miracle-wm"
