#!/usr/bin/env bash

set -euo pipefail

mkdir -p /var/lib/dank-bluebuild/skel-init
mkdir -p /var/lib/dank-bluebuild/post-login-setup/script.d

[ -e "/var/lib/dank-bluebuild/skel-init/run.completed" ] && exit 0

SKEL="/etc/skel"

awk -F: '$3 >= 1000 && $3 < 65534 { print $1 ":" $6 }' /etc/passwd |
while IFS=: read -r user home; do
    [[ -d "$home" ]] || continue
    [[ -f "$home/.local/state/dank-bluebuild/skel-init/run.completed" ]] && continue

    rsync --backup --suffix=.skel-init.bak "$SKEL"/ "$home"/
    chown -R "$user:$user" "$home"
    chmod -R 700 "$home"
done

