#!/usr/bin/env bash

set -euo pipefail

[ "$EUID" -eq 0 ] && exit 1

[ -f "/var/lib/dank-bluebuild/post-login-setup/auto.disabled" ] && exit 0

scripts=( /usr/libexec/dank-bluebuild/post-login-setup/script.d/* )
scripts_completed=( "${scripts[@]/%/\.completed}" )
completed_scripts=( /var/lib/dank-bluebuild/post-login-setup/script.d/* )

[[ "${scripts_completed[*]}" == "${completed_scripts[*]}" ]] && exit 0

xdg-terminal-exec -e bash -c "/usr/libexec/dank-bluebuild/post-login-setup/run; exec bash"
