#!/usr/bin/env bash

set -euo pipefail

[ "$EUID" -eq 0 ] && exit 1

if [ -f /var/lib/dank-bluebuild/post-login-setup.done ]; then
    mv "$HOME/.config/autostart/post-login-setup.desktop" "$HOME/.config/autostart/post-login-setup.desktop.lock"
    exit 0
fi

scripts=( /usr/libexec/dank-bluebuild/post-login-setup/script.d/* )
completed_scripts=( /var/lib/dank-bluebuild/post-login-setup/script.d/* )

scripts_done=( "${scripts[@]/%/\.done}" )
if [[ "${scripts_done[*]}" == "${completed_scripts[*]}" ]]; then
    mv "$HOME/.config/autostart/post-login-setup.desktop" "$HOME/.config/autostart/post-login-setup.desktop.lock"
    exit 0
fi

xdg-terminal-exec -e bash -c "/usr/libexec/dank-bluebuild/post-login-setup/run; exec bash"
