#!/usr/bin/env bash

set -euo pipefail

disable_autostart() {
    sudo touch /var/lib/dank-bluebuild/post-login-setup.done

    if [[ -f "/etc/xdg/autostart/post-login-setup.desktop" ]]; then
        echo "Disabling setup autostart..."
        if sudo mv "/etc/xdg/autostart/post-login-setup.desktop" "/etc/xdg/autostart/post-login-setup.desktop.lock"; then
            echo "Successfully disabled autostart for setup."
            return 0
        else
            echo "Failed to disable autostart for setup." >&2
            echo "You can manually disable the autostart by locking or removing the file '/etc/xdg/autostart/post-login-setup.desktop'."
            return 1
        fi
    fi
}

autostart_prompt() {
    echo "Allow this script to automatically run again on next login to retry/complete desktop setup? (Y/n)"
    read -r response
    case "$response" in
        [Yy]* | "" )
            echo "The desktop setup will autostart again on next login."
            ;;
        [Nn]* )
            disable_autostart || echo "The desktop setup might autostart again on next login."
            ;;
        * )
            echo "Invalid response. Please enter y or n."
            autostart_prompt
            ;;
    esac

    echo "You can manually run the setup again by running 'post-login-setup' with or without sudo."
}

echo "### DANK BLUE BUILD SETUP ###"
echo "You can review the contents of this setup in '/usr/local/bin/post-login-setup' and '/usr/libexec/dank-bluebuild/setup.d/' before you proceed."

if [ "$EUID" -ne 0 ]; then
    echo "This setup requires sudo privileges."
    echo "Requesting sudo privileges... (Press Ctrl+C to cancel)"

    if sudo -v &> /dev/null; then
        echo "Sudo privileges granted."
    else
        echo "Failed to obtain sudo privileges." >&2
        autostart_prompt
        exec bash
    fi
else
    read -r -p "Press Enter to continue or Ctrl+C to cancel."
fi

while true; do
    sleep 60
    sudo -v
done &
SUDO_LOOP_PID=$!

exit_script() {
    kill "$SUDO_LOOP_PID" 2>/dev/null
    sudo -K
}
trap exit_script EXIT

declare -a FAILED_SCRIPTS=()

abort_script() {
    echo "Setup interrupted." >&2
    autostart_prompt
    exit_script
}
trap abort_script INT

STATE_PATH="/var/lib/dank-bluebuild/post-login-setup/script.d"
mkdir -p "$STATE_PATH"

SCRIPT_DIR="/usr/libexec/dank-bluebuild/post-login-setup/script.d"
shopt -s extglob nullglob
SCRIPTS=( "$SCRIPT_DIR"/!(example) )

exec > >(sudo tee -a /var/lib/dank-bluebuild/post-login-setup/log) 2>&1   

if [ "${#SCRIPTS[@]}" -ne 0 ]; then
    for script in "${SCRIPTS[@]}"; do
        if [ -f "$STATE_PATH/$(basename "$script").done" ]; then
            echo "Script '$script' already completed. Skipping..."
            continue
        fi

        echo "Executing '$script'..."
        if ! sudo bash "$script"; then
            FAILED_SCRIPTS+=("$script")
        else
            touch "$STATE_PATH/$(basename "$script").done"
        fi
    done
fi

if [ ${#FAILED_SCRIPTS[@]} -ne 0 ]; then
    echo "The following scripts failed during setup:" >&2
    for script in "${FAILED_SCRIPTS[@]}"; do
        echo "  - $script" >&2
    done

    echo "Please review the errors above. See the log file '/var/lib/dank-bluebuild/post-login-setup/log'." >&2
    autostart_prompt
    exit_script
else
    disable_autostart
    echo "All scripts executed successfully. "
    echo "Setup completed."
    exit_script
fi